### ISSUE TITLE
请问是否支持自己安装的RocketMQ呢？

### ISSUE THREAD

**Issue by realdog** [XadillaX/aliyun-ons#1]
如题如题

**Comment by XadillaX** [comment]
这个我并不是很清楚，我是使用了[这里](https://help.aliyun.com/document_detail/ons/sdk/cpp-sdk/set-env.html?spm=5176.product8315024_ons.4.14.ROqDsY)的 SDK。

你可以问问阿里云的客服，他们的 C++ SDK 是否支持。
