### ISSUE TITLE
一个关于ONS的问题，并不是真的issue: ）

### ISSUE THREAD

**Issue by ChenLi0830** [XadillaX/aliyun-ons#13]
谢谢你的repo，非常有帮助。
我刚接触ONS，读example代码的时候有两个基础的问题：
1. consumer是怎么保证自己在忙的时候暂时不从producer获取message的呢？
2. 假如一个topic有多个consumer，如何有效分配哪个consumer处理哪个message，并且不出现重复处理同一个message的情况呢?

**Comment by XadillaX** [comment]
你这些问题并不是该 SDK 的问题，而是阿里云 ONS 本身的设计问题。

1. 阿里云 ONS 设计如此，无法保证。
2. 可以咨询阿里云的技术支持，开工单。

**Comment by ChenLi0830** [comment]
@XadillaX 好的，谢谢
