### ISSUE TITLE
linux里require出现以下异常

### ISSUE THREAD

**Issue by wb-xiaoduan** [XadillaX/aliyun-ons#14]
TypeError: invalid data
    at WriteStream.Socket.write (net.js:625:11)
    at /acs/upload/node_modules/ons/lib/_stdout.js:36:34
    at Array.forEach (native)
    at Object.exports.restoreStdout (/acs/upload/node_modules/ons/lib/_stdout.js:35:13)
    at /acs/upload/node_modules/ons/lib/producer.js:47:33

**Comment by XadillaX** [comment]
你怎么写的？

**Comment by wb-xiaoduan** [comment]
var Producer = require("ons").Producer;
var producer = new Producer('PID-xxx', 'xxx', 'xxx', {
    namesrvAddr: "112.124.141.191:80",
    onsAddr: "http://onsaddr-internet.aliyun.com:80/rocketmq/nsaddr4client-internet",
    sendTimeout: 1000
});
producer.start(function(err) {
    if (err) return console.log(err);
    console.log("Started!");
});
producer.send('wed22', 'TAGS', 'CONTENT', function(err, messageId) {
    console.log(arguments);
});

**Comment by wb-xiaoduan** [comment]
exports.restoreStdout = function() {
    if(!ref) return;

    ref--;
    if(!ref) {
        process.stdout.write = origStdoutWrite;

        buf.forEach(function(b) {
           #  process.stdout.write.call(process.stdout, b);
        });
        buf = [];
    }
};

**Comment by wb-xiaoduan** [comment]
{ '0': [Error: This ONS producer is not started.] }
Started!

**Comment by wb-xiaoduan** [comment]
还在吗？

**Comment by XadillaX** [comment]
```javascript
namesrvAddr: "112.124.141.191:80",
onsAddr: "http://onsaddr-internet.aliyun.com:80/rocketmq/nsaddr4client-internet",
```

这两个参数在你不知道作用的情况下，不需要自定义。

**Comment by wb-xiaoduan** [comment]
{ '0': [Error: This ONS producer is not started.] }还是提示这个。没有具体的原因

**Comment by XadillaX** [comment]
你的 send 要写在 start 的 callback 里面
