### ISSUE TITLE
windows 平台 Error: Topic Route does not exist

### ISSUE THREAD

**Issue by DAppx** [XadillaX/aliyun-ons#15]
example /  producer.js 
 提示 Error: Topic Route does not exist

consumer.js  测试 OK

同样的代码在 LInux Centos6.5/7 下 运行正常

win8.1 64位 msvs_version 2015 编译  node v6.2.0 npm 3.10.7

**Comment by DAppx** [comment]
![1222](https://cloud.githubusercontent.com/assets/15499011/18160401/ecf06e2e-705f-11e6-9fea-6d96565e0272.png)

**Comment by DAppx** [comment]
window 下编译时，出现 许多的  warning ,是否与此有关？

 C:\Users\chengdi\.node-gyp\6.2.0\include\node\v8.h(3239): note: see declarati
  on of 'v8::Function::NewInstance'
..\src\producer.cpp : warning C4819: The file contains a character that cannot
be represented in the current code page (936). Save the file in Unicode format
to prevent data loss [D:\cdwork\react-native-test\f8app\node_modules\ons\build\
ons.vcxproj]
..\src\consumer_listener.cpp : warning C4819: The file contains a character tha
t cannot be represented in the current code page (936). Save the file in Unicod
e format to prevent data loss [D:\cdwork\react-native-test\f8app\node_modules\o
ns\build\ons.vcxproj]
..\src\consumer.cpp(270): warning C4996: 'v8::Function::NewInstance': was decla
red deprecated [D:\cdwork\react-native-test\f8app\node_modules\ons\build\ons.vc
xproj]

**Comment by XadillaX** [comment]
https://github.com/alibaba/ons/issues/7

请参照这里。

**Comment by DAppx** [comment]
sendTimeout: 10000   try OK
 . thanks
