### ISSUE TITLE
producer 如何指定 mqttSecondTopic，两个consumer 消息会重复怎么搞

### ISSUE THREAD

**Issue by qiu-xm** [XadillaX/aliyun-ons#20]
1、关于 MQTT 收到 procuder 发布的消息问题
如果不指定 mqttSecondTopic ，MQTT端就收不到消息了

2、同时启动两个consumer，消息会重复问题
启动一个 procuder，每100ms发一条消息
启动两个 consumer 收消息，两个 consumer 收到的消息会重复【有ack.done()】
OMG，这应该是aliyun的问题吧。。。

谢谢

**Comment by XadillaX** [comment]
这里用的是阿里云 C++ 版的 SDK，并没有走 MQTT 协议，其所有功能都是基于其 [C++ SDK](https://help.aliyun.com/document_detail/29556.html?spm=5176.doc29555.6.580.6xIJzs) 来的。

**Comment by XadillaX** [comment]
如果是消息重复应该是阿里云自身的问题，可以提 Issue 给他们的客服看。
