### ISSUE TITLE
提示  Segmentation fault

### ISSUE THREAD

**Issue by 2695691406** [XadillaX/aliyun-ons#22]
我按照你的文档去安装和配置，消费者初始化的时候报错Segmentation fault

**Comment by XadillaX** [comment]
能把详细的代码以及错误信息发出来吗？

**Comment by XadillaX** [comment]
还有问题吗？

**Comment by bananafishM** [comment]
Ubuntu 16.04.3下出现了同样的提示
实例创建之后, 代码在调用init的时候出错
下面是创建实例的代码: 
![image](https://user-images.githubusercontent.com/13161817/32888960-f6c0e15e-cb03-11e7-8ae2-13df8a72ef9e.png)

运行结果:
![image](https://user-images.githubusercontent.com/13161817/32889018-22a4df78-cb04-11e7-8973-c5f8f680d1a5.png)

换了淘宝源安装依旧不行, 下面是淘宝源装包时的输出信息
![image](https://user-images.githubusercontent.com/13161817/32889067-4f03faf4-cb04-11e7-976d-80278a1a03df.png)

能帮忙看一下是什么问题吗?

**Comment by XadillaX** [comment]
经验证，这个 SDK 的确在 Ubuntu 16.04 下无法正常执行。

根本原因好像是 G++ 版本不一致导致的，阿里云官方的 C++ SDK 是在 4.x 下编译的，而据说 16.04 下的 G++ 是 5.x，导致不兼容。

**Comment by bananafishM** [comment]
谢谢! 的确是这个原因.
前面按提示修改了node-gyp的编译警告, node-gyp编译正常不过还是运行失败.

把 G++ 降级到 4.8 后 重新编译运行成功了~!🙏🏻 ✨

另外阿里云那边的MQ服务HTTP协议下架了...mac党哭晕在厕所
