### ISSUE TITLE
[需求]作者有没有计划基于RocketMQ来实现

### ISSUE THREAD

**Issue by icyblazek** [XadillaX/aliyun-ons#25]
不知道作者有没有计划做支持？没有具体研究基于ONS和基于RocketM差异多大，理论上应该不大，看了一下源码，想提个PR支持，但看了一下，要熟悉整个项目才好动手，不知道作者看是否列入计划中？

**Comment by XadillaX** [comment]
暂时没有，因为 rocketmq 的协议没有一个成型的文档，其它语言的 sdk 代码都略晦涩，很难系统地实现客户端协议。

等 rocketmq 有一份完整的文档之后会根据协议实现一份。

**Comment by icyblazek** [comment]
OK，目前确实是个大的麻烦，持续关注吧

**Comment by fengmk2** [comment]
其实已经实现了，可以参考 https://github.com/ali-sdk/ali-ons

**Comment by XadillaX** [comment]
@fengmk，来抢生意了😂

说实话，纯扒 java 吃相太难看，还是看得云里雾里_(:3」∠❀)_

**Comment by fengmk2** [comment]
@XadillaX 必然不是照代码画葫芦，肯定是通过代码理解整个通信原理。
