### ISSUE TITLE
Working with a local instance of RocketMq

### ISSUE THREAD

**Issue by OlivierAlbertini** [XadillaX/aliyun-ons#28]
Hi,

I have a question about your library. Is it compatible with a local RocketMQ server ?
I followed the get started documentation here: http://rocketmq.incubator.apache.org/docs/quick-start/. Everything works fine but I can't figure out how to make it work with this lib. perhaps it's just the config... is it possible to add an example in your example folder that is compatible with the get started doc or just compatible with local server (with a default config, e.g localhost:9876).

Any help will be appreciate.. Thanks

**Comment by XadillaX** [comment]
Unfortunately, this does not support for local RocketMQ so far. Because this SDK is based on Aliyun ONS C++ SDK.

Maybe after the protocol document finishing, we can start to figure this out.
