### ISSUE TITLE
内存泄露 , CPU 占用过高

### ISSUE THREAD

**Issue by sandwich99** [XadillaX/aliyun-ons#7]
```javascript
const Ons = require('ons');
const Consumer = Ons.Consumer;

const CONSUMER_ID = 'CID-EVENT-***';
const TOPIC = 'TERMINAL-MQ-****';
const ACCESS_KEY = '********************';
const SECRET_KEY = '********************************';

const consumer = new Consumer(CONSUMER_ID, TOPIC, '*', ACCESS_KEY, SECRET_KEY);

consumer.on('message', (msg, ack) => {
    ack.done();
});

consumer.init((err) => {
    if(err) {
        console.log(err);
    } else {
        console.log('开始监听 ons!');
        consumer.listen();
    }
    console.log('ons started!!');
});
```

该代码会导致内存持续上升, 并且消息处理完之后 CPU 使用率也不会下降

重启服务经常会报
```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::thread_resource_error> >'
  what():  boost::thread_resource_error: Resource temporarily unavailable
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::thread_resource_error> >'Aborted
live@biz26:/data/projects/pusher$ terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::erro
```

**Comment by XadillaX** [comment]
今天上午排查一下

**Comment by XadillaX** [comment]
不确定真的完全修复，不过可以试试新的 1.5.0。

如果还有问题可能要思考下官方 C++ 版的 SDK 了。

**Comment by sandwich99** [comment]
依然内存泄露

**Comment by XadillaX** [comment]
#9

**Comment by XadillaX** [comment]
关于

> 重启服务经常会报
>
> ```
> terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::thread_resource_error> >'
  what():  boost::thread_resource_error: Resource temporarily unavailable
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::thread_resource_error> >'Aborted
live@biz26:/data/projects/pusher$ terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::erro

这一条是因为程序退出了然后 ONS 官方 C++ SDK 的线程还没完全退出导致的。

在接下去发的版本里面会强调这个问题，退出之前需要先把启动的 ONS 给 `stop()` 掉才行，`1.5.0` 其实也可以这么支持了。

```javascript
process.on("SIGINT", function() {
    consumer.stop();
});
```

上面只是一个例子。

对于内存泄露和 CPU 过高的问题，我还在复现——好像我这边暂时并没有复现。

**Comment by sandwich99** [comment]
加入了上述代码, 5分钟了..
进程还没有结束
![image](https://cloud.githubusercontent.com/assets/1179783/16830795/af8190c0-49d3-11e6-8fd4-645d8be0d213.png)

**Comment by XadillaX** [comment]
@sandwich99 

```javascript
process.on("SIGINT", function() {
    consumer.stop();
    process.exit(0);
});
```

**Comment by sandwich99** [comment]
实测加入 process.exit(0); 对正常结束进程, 并没有帮助

运行该代码 8分钟, 内存使用上升了4倍
![image](https://cloud.githubusercontent.com/assets/1179783/16831129/c82e9198-49d5-11e6-9dc2-5f58ed38cb4b.png)

从20M, 上升到 80M..并且在持续上升

**Comment by XadillaX** [comment]
问一下出现这个问题的确实是 `consumer` 而不是 `producer`？

**Comment by sandwich99** [comment]
是 consumer

Get Outlook for iOS




On Mon, Jul 18, 2016 at 11:58 PM +0800, "Flandre Scarlet" <notifications@github.com> wrote:












问一下出现这个问题的确实是 consumer 而不是 producer？

**Comment by XadillaX** [comment]
从目前阿里云 ONS C++ SDK 开发者的反馈来看，这应该不是内存泄露，并且是一个 feature 而不是 bug，并不是我这边能阻止的，因为我是基于 C++ SDK 封装的。

详情可以参考 https://github.com/XadillaX/aliyun-ons/issues/8#issuecomment-233607029。
