### ISSUE TITLE
内存泄露 , CPU 占用过高

### ISSUE THREAD

**Issue by lucaszong** [XadillaX/aliyun-ons#8]
与上位仁兄一样的代码，、
配置：1核1g内存。pm2守护
消费情况：一个对列，一个consumer，持续不间断消费
结果：大约每隔2小时，内存100%，cpu100%，然后进程重启

**Comment by XadillaX** [comment]
我今天上午排查一下

**Comment by XadillaX** [comment]
#7 

不确定真的完全修复，不过可以试试新的 1.5.0。

如果还有问题可能要思考下官方 C++ 版的 SDK 了。

**Comment by XadillaX** [comment]
#9

**Comment by XadillaX** [comment]
是 `consumer` 还是 `producer`？

**Comment by lucaszong** [comment]
是consumer, 现在使用最新的1.5.0，内存不高了，但持续消费48小时左右，我的pm2会重启。 
producer我暂时还没有使用。

**Comment by lucaszong** [comment]
是consumer, 内存不高了，只是涨的缓慢，
具体是在运行24小时左右，内存会涨一倍，我这边是从120M~228M。
然后再约48小时左右，pm2会重启，此时内存远没到顶峰

**Comment by XadillaX** [comment]
@lucaszong 我从阿里云 C++ SDK 作者那边了解到

> C++ SDK 会开一个线程，持续不断（也就是不管你这边消费 Ack 的进度）去远程拉消息到内存给应用程序慢慢消费。

也就是说如果堆积的消息太多，内存是会持续增长的。

最后得出的结论并不是我这边 SDK 的内存泄露，而是因为 C++ SDK 的 feature 以及你自身的消息堆积过大。

看你现在说的：

> 是consumer, 内存不高了，只是涨的缓慢，
>
> 具体是在运行24小时左右，内存会涨一倍，我这边是从120M~228M。
>
> 然后再约48小时左右，pm2会重启，此时内存远没到顶峰

目测你的堆积已消费完，达到一个消费生产平衡的状态，或者你把消费点重置了，导致内存正常。

所以目前来算这不算 Bug。

到时候我会把 libuv 层的优化合到主分支并发一个新版本。

**Comment by lucaszong** [comment]
正常情况下，堆积：10-50条左右，消费TPS：43.42条/秒
每日18：00左右，会有一个高峰（与具体业务有关），堆积：3000条左右，随后堆积恢复正常，

内存始终缓慢增长，从没有重置过消费点；只有在pm2重启此进程后，内存才恢复。
（这个pm2自动重启此进程，暂时无法确定是否与此相关。但可以肯定的是在不使用此包情况下，pm2不会重启）

最后，很期待你的新版本

**Comment by sandwich99** [comment]
个人感觉, 开一个独立线程去拉到本地堆积消息是 SDK 为了增加吞吐量而设计的 feature
SDK 内部应该实现了相应的拥塞控制, 根据客户端处理消息的吞吐量弹性的去消息队列里拉数据到本地

这和内存 / CPU 持续增长无关, 最多本地堆积的消息会占用一部分内存, 随着消费, 这部分内存应该释放掉

不负责推测:  ack.done 方法的实现里是不是和 C++ 包集成有问题?

C ++ 代码确实看不懂... 只能推测了

麻烦了, 谢谢

**Comment by XadillaX** [comment]
他们的 SDK 没有做任何限流，之前就是测试堆积了很多然后赶不上消费会导致内存剧增。

其它情况下好像还没有检测到任何内存异常的情况。

**Comment by XadillaX** [comment]
我的进程目前的一个循环：

开始（150M）-> 180M -> 220M -> 250M -> 280M -(GC)-> 150M

就是 GC 比较不频繁，实际上是会掉回去的。

**Comment by sandwich99** [comment]
CPU 占用持续增长, 消息消费完了也不会降低
![image](https://cloud.githubusercontent.com/assets/1179783/17048382/2933b912-5018-11e6-8256-aab6da925e0e.png)

**Comment by lucaszong** [comment]
这是为啥？？
SystemService-0 (err): 2016 - 07 - 27 10: 00 +08:00: terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::thread_resource_error> >'
SystemService-0 (err): 2016 - 07 - 27 10: 00 +08:00:   what():  boost::thread_resource_error: Resource temporarily unavailable
SystemService-0 (err): 2016 - 07 - 27 10: 02 +08:00: terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::thread_resource_error> >'
SystemService-0 (err): 2016 - 07 - 27 10: 02 +08:00:   what():  boost::thread_resource_error: Resource temporarily unavailable
SystemService-0 (err): 2016 - 07 - 27 10: 07 +08:00: terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::thread_resource_error> >'
SystemService-0 (err): 2016 - 07 - 27 10: 07 +08:00:   what():  boost::thread_resource_error: Resource temporarily unavailable
SystemService-0 (err): 2016 - 07 - 27 10: 08 +08:00: terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::thread_resource_error> >'
SystemService-0 (err): 2016 - 07 - 27 10: 08 +08:00:   what():  boost::thread_resource_error: Resource temporarily unavailable
SystemService-0 (err): 2016 - 07 - 27 17: 07 +08:00: terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::thread_resource_error> >'
SystemService-0 (err):   what():  boost::thread_resource_error: Resource temporarily unavailable
SystemService-0 (err): 2016 - 07 - 27 17: 09 +08:00: terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::thread_resource_error> >'
SystemService-0 (err): 2016 - 07 - 27 17: 09 +08:00:   what():  boost::thread_resource_error: Resource temporarily unavailable
SystemService-0 (err): 2016 - 07 - 27 17: 25 +08:00: terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::thread_resource_error> >'
SystemService-0 (err): 2016 - 07 - 27 17: 25 +08:00:   what():  boost::thread_resource_error: Resource temporarily unavailable
SystemService-0 (err): 2016 - 07 - 27 18: 05 +08:00: terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::thread_resource_error> >'
SystemService-0 (err): 2016 - 07 - 27 18: 05 +08:00:   what():  boost::thread_resource_error: Resource temporarily unavailable
SystemService-0 (err): 2016 - 07 - 27 18: 07 +08:00: terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::thread_resource_error> >'
SystemService-0 (err): 2016 - 07 - 27 18: 07 +08:00:   what():  boost::thread_resource_error: Resource temporarily unavailable
SystemService-0 (err): 2016 - 07 - 27 21: 50 +08:00: terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::thread_resource_error> >'
SystemService-0 (err): 2016 - 07 - 27 21: 50 +08:00:   what():  boost::thread_resource_error: Resource temporarily unavailable

**Comment by XadillaX** [comment]
@lucaszong 其实这对于整个程序来说没有多大影响。

另外，你结束进程的时候有 `stop` 你的 `consumer` 或者 `producer` 么？

**Comment by lucaszong** [comment]
自从上次使用了你的新包后，内存倒还好，但一天当中，终会有4-5次cpu超过90%，然后消费速度很慢，跟不上生成速度，导致不断堆积消息。（在ali的ons控制台中显示消费速度29.2条/秒，堆积211584条。pm2显示在重启后app已持续运行6h）
app重启后，消费正常，但维持不了几个小时，问题又重现。（且在重启那一刹那，cpu还是很高的，）

**Comment by lucaszong** [comment]
结束进程的时候已经 stop 了 consumer

**Comment by XadillaX** [comment]
@lucaszong 你用的是哪个版本的包？

**Comment by lucaszong** [comment]
当前使用的是1.5.0

在2.2.2不能用。
安装编译时警告：

npm install ons --save --registry=https://registry.npm.taobao.org
npm WARN package.json mbs@1.0.0 No description
npm WARN package.json mbs@1.0.0 No repository field.
npm WARN package.json mbs@1.0.0 No README data
-
> ons@2.2.2 install /mbs/node_modules/ons
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory `/mbs/node_modules/ons/build'
  CXX(target) Release/obj.target/ons/src/entry.o
  CXX(target) Release/obj.target/ons/src/ons_options.o
  CXX(target) Release/obj.target/ons/src/consumer_ack.o
  CXX(target) Release/obj.target/ons/src/consumer.o
  CXX(target) Release/obj.target/ons/src/producer.o
In file included from ../src/producer.cpp:28:0:
../src/producer_workers/producer_prepare_worker.h: In constructor ‘ProducerPrepareWorker::ProducerPrepareWorker(Nan::Callback*, ONSProducerV8&, std::string, int)’:
../src/producer_workers/producer_prepare_worker.h:72:12: **warning: ‘ProducerPrepareWorker::uuid’ will be initialized after [-Wreorder]
     string uuid;
            ^
../src/producer_workers/producer_prepare_worker.h:71:9: warning:   ‘int ProducerPrepareWorker::stdout_fd’ [-Wreorder]
     int stdout_fd;
         ^**
../src/producer_workers/producer_prepare_worker.h:24:5: warning:   when initialized here [-Wreorder]
     ProducerPrepareWorker(Nan::Callback* callback, ONSProducerV8& ons, string u4, int stdout_fd) :
     ^
  CXX(target) Release/obj.target/ons/src/consumer_listener.o
  CXX(target) Release/obj.target/ons/src/third_party/sole/sole.o
  SOLINK_MODULE(target) Release/obj.target/ons.node
  COPY Release/ons.node
make: Leaving directory `/mbs/node_modules/ons/build'
ons@2.2.2 node_modules/ons
├── nan@2.4.0
└── lei-stream@1.2.0 (lei-utils@2.1.0, debug@2.2.0, async@2.0.1)

运行时抛错：
onsconsumer-0 terminate called after throwing an instance of 'std::bad_alloc'
onsconsumer-0   what():  std::bad_alloc
onsconsumer-0 mysql connect success
onsconsumer-0 mysql connect success
onsconsumer-0 mysql connect success
onsconsumer-0 mysql connect success
onsconsumer-0 terminate called after throwing an instance of 'std::bad_alloc'
onsconsumer-0   what():  std::bad_alloc
onsconsumer-0 mysql connect success
onsconsumer-0 mysql connect success
onsconsumer-0 mysql connect success
onsconsumer-0 mysql connect success
onsconsumer-0 terminate called after throwing an instance of 'std::bad_alloc'
